### ISSUE TITLE
Dual Extruders

### ISSUE THREAD

**Issue by Bluemalu** [tohara/OctoPrint-Pidtune#1]
The plug-in parses the default extruder only (Too0) for the PID values. The setup allows me to choose either Tool0, Tool1 or the bed.  The apply and save functions work correctly and store the new values (although save is blanked out for the bed).

In short, when parsing the EEPROM could you add the E0 or E1 to the script please.

**Comment by Bluemalu** [comment]
Sorry, I was wrong, the new values don't get updated to Tool 1 they were artifacts from the initial definitions.

**Comment by tohara** [comment]
I have now updated  as per your request, but have not actually tested with dual PID settings enabled in firmware. Have only tested for backwards compatibility. I would appreciate if you could test this an let me know if there is any issues.

I was not aware that the Bed PID setting are now stored in EEprom as well. Have enabled the save button when bed is selected.

**Comment by Bluemalu** [comment]
Not a problem I will test it today.
Many thanks
Drew
On 25 Jun 2016 08:36, tohara notifications@github.com wrote:I have now updated  as per your request, but have not actually tested with dual PID settings enabled in firmware. Have only tested for backwards compatibility. I would appreciate if you could test this an let me know if there is any issues.

I was not aware that the Bed PID setting are now stored in EEprom as well. Have enabled the save button when bed is selected.

**Comment by Bluemalu** [comment]
All tested, works perfectly.

I had to download the plugin again and apply the updated files.

Octoprint recognised the updated files and carried out the update.

Read the EEPROM data from both Tools (0/1) and then carried out a PID tune of both heads.  Not quite sure the difference between the Apply and Save buttons (unless one applies the values and the other saves it to the EEPROM (seem obvious now I've just written it down)).  Both have taken and printer power cycled to confirm the values have taken.

Once again many thanks

Drew

-----Original Message-----

**Comment by tohara** [comment]
Thank you Drew.

Apply and Save: As you said :),  Apply sends the command M301 P I D and Save sends the command M500 to the controller.
